server:
  port: 8081

spring:
  application:
    name: order-service

eureka:
  instance:
    hostname: localhost  # Explicitly set the hostname
    prefer-ip-address: true  # Register with IP instead of hostname
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/